# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiddenGems' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiddenGems
   pod 'Parse'
   pod "AlamofireImage"
   pod "MessageInputBar"


  target 'HiddenGemsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiddenGemsUITests' do
    # Pods for testing
  end


end
